[env]
platform = espressif32
board = deneyapkart
framework = arduino
monitor_speed = 115200
upload_speed = 921600 
lib_deps = 
    madhephaestus/ESP32Servo@^3.0.5
    https://github.com/ZZ-Cat/CRSFforArduino.git
    miguelbalboa/MFRC522
    adafruit/Adafruit GFX Library@^1.11.5
    adafruit/Adafruit SSD1306@^2.5.7

[env:sub_deneyap]
build_src_filter = 
    +<sub_deneyap.cpp>
    +<ctype_fix.c>
    +<tasks_sub_deneyap/*.cpp>


[env:main_deneyap]
build_src_filter = 
    +<main_deneyap.cpp>
    +<ctype_fix.c>
    +<tasks_main_deneyap/*.cpp>
